version: "3.7"

services:

  db:
    image: postgres:13.6-alpine
    restart: always
    env_file: .env
    ports:
      - "4011:5432"

  migrate:
    image: migrate/migrate
    env_file: .env
    depends_on:
      - db
    links:
      - db
    volumes:
      - "./../db/migrations:/database"
    command:
      [ "-path", "/database", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable", "up" ]

  app:
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3333:3333"
